// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlbiqpccnddamdxczfef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sYmlxcGNjbmRkYW1keGN6ZmVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTEwMDUsImV4cCI6MjA2NjI4NzAwNX0.q_0gDkrwipi6phoOfhsSKblkol-dKuITee9x-AmyPUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);